[pytest]
markers =
    smoke: fast tests
    regression: regression tests
    slow: slow tests
    api: api tests
    ui: ui tests
    db: db tests
    accessibility: a11y tests
    flaky: flaky tests
    negative: negative tests
    positive: positive tests
log_cli = 1
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format=%Y-%m-%d %H:%M:%S